apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-mosaic
  namespace: argo-workflows

spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: argo-workflows-executor

  podGC:
    strategy: OnPodSuccess

  ttlStrategy:
    secondsAfterSuccess: 5000
    secondsAfterFailure: 5000

  artifactGC:
    strategy: OnWorkflowDeletion
    forceFinalizerRemoval: true

  # nodeSelector:
  #   data-production: r12xlarge # ?
  # tolerations:
  #   - key: data-production
  #     operator: Equal
  #     value: r12xlarge # ?
  #     effect: NoSchedule

  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"

  parallelism: 5

  arguments:
    parameters:
      - name: image-name # ?
        value: "686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/geomad:v20260721-1007"
      - name: version
        value: "1.0.0"
      - name: output-bucket
        value: piksel-staging-public-data
      # - name: output-path
      #   value: geomad_s2
      - name: years
        # value: '["2017","2018","2019","2020","2021","2022","2023","2024","2025"]'
        value: '["2021"]' # As of 2026-07-20: 2020-2025 completed, 2019 processing, 2017-2018 not started.
      - name: product
        value: s2_geomad_annual
      # TODO: needed? It is auto.
      # - name: out-product
      #   value: geomad_s2_annual_mosaic_120
      - name: period
        value: P1Y
      - name: bands
        value: red,green,blue,rededge1,rededge2,rededge3,nir,nir08,swir16,swir22,BCMAD,EMAD,SMAD,COUNT
      - name: resolution
        value: "120"
      - name: split-bands
        value: "true"
      - name: overwrite
        value: "true"

  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: create-low-res-mosaic-per-year
            template: create-low-res-mosaic
            arguments:
              parameters:
                - name: year
                  value: "{{item}}"
            withParam: "{{workflow.parameters.years}}"

    - name: create-low-res-mosaic
      inputs:
        parameters:
          - name: year

      container:
        image: "{{workflow.parameters.image-name}}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 16Gi # TODO: Tune.
            cpu: 2
          limits:
            memory: 32Gi
            cpu: 4

        env:
          - name: AWS_DEFAULT_REGION
            value: "ap-southeast-3"
          - name: DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: ODC_DEFAULT_DB_PORT
            value: "6432"
          - name: ODC_DEFAULT_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: ODC_DEFAULT_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: odc
                key: username # TODO: Fix username used as db name

        command: ["/entrypoint.sh"]
        args:
          - /bin/bash
          - "-c"
          - |
            set -ex
            python /app/src/low_res_mosaic/low_res_mosaic.py \
              --product "{{workflow.parameters.product}}" \
              --version "{{workflow.parameters.version}}" \
              --time-start "{{inputs.parameters.year}}" \
              --period "{{workflow.parameters.period}}" \
              --bands "{{workflow.parameters.bands}}" \
              --resolution "{{workflow.parameters.resolution}}" \
              --s3-output-root "s3://{{workflow.parameters.output-bucket}}/" \
              $( [ "{{workflow.parameters.split-bands}}" = "true" ] && echo --split-bands ) \
              $( [ "{{workflow.parameters.overwrite}}" = "true" ] && echo --overwrite )
